<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_descripcion_servicios  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		$user=$_SESSION['UserID'];
$permiso=Security::getUserGroup();
if($permiso<>'SuperAdmin'){


$rs = DB::Query("select id_User from usuario where Usuario='".$user."'");
$data=$rs->fetchAssoc();

var_dump(data);

$id_laboratorio = DB::Query("select id_Laboratorio from Laboratorio where fk_id_User='".$data['id_User']."'");
$response = $id_laboratorio->fetchAssoc();
var_dump(response);

}else{}
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
