<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_servicios1  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		
// Obtén el valor del campo "Tipo Servicio"
$tipoServicio = $values['TipoServicio'];

// Define la URL de redirección basada en el valor del campo "Tipo Servicio"
$redirectUrl = "";
if ($tipoServicio == "CALIBRACION") {
$redirectUrl = "calibracion_add.php";
} elseif ($tipoServicio == "ENSAYO") {
$redirectUrl = "ensayo_add.php";
}

// Si se ha definido una URL de redirección, genera el código HTML para redirigir
if (!empty($redirectUrl)) {
$html =
"<script>
window.open('".$redirectUrl."');
</script>";
echo $html;
exit();
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
