<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_servicios  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeAdd"]=true;




	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		/* $User = $_SESSION['UserID'];

// Comprobar si existe un registro específico
$consulta = DB::Query("SELECT id_Laboratorio FROM laboratorio WHERE fk_id_User='$User'");
$data = $consulta->fetchAssoc();

$values['fk_id_Laboratorio'] = $data['id_Laboratorio'];

if ($id_User == 2 || $id_User == 3) {
    $query->addWhere("fk_id_User=".$id_User);
} else {
// Consulta principal con JOIN
$query = "SELECT s.id_Servicio, s.Nombre_Servicio, s.Norma_Requerida, s.Observaciones, s.Valor_Servicio, s.Tipo_Servicio, s.fk_id_Laboratorio, fk_id_User
FROM servicio s 
JOIN laboratorio l ON s.fk_id_Laboratorio = l.id_Laboratorio
JOIN usuario u ON l.fk_id_User = u.id_User
WHERE l.fk_id_User = '$id_User'";
}

// Ejecutar la consulta
$result = DB::Query($query); */

return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
